### PR TITLE
suite of website-tests

### PR DESCRIPTION
**Pull request by kwhitehall**
I am not certain where we should put these. @chrismattmann where do you think is best?

### CODE REVIEW

**Comment by chrismattmann** [comment]
good question @kwhitehall How about in a folder called tests?

**Comment by kwhitehall** [comment]
Hmm... that works, but if is in the main folder it will be pull hourly for updates?

**Comment by chrismattmann** [comment]
hey @kwhitehall sure it will be pulled, but that's not a huge deal, right?

**Comment by kwhitehall** [comment]
@chrismattmann  that makes sense. Will update the robots.txt to disallow that location.

**Comment by kwhitehall** [comment]
@chrismattmann new PR sent.

**Pull request closed without merging**
